//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace apex_runner.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.11.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files (x86)\\Netease\\UU\\launcher.exe")]
        public string uupath {
            get {
                return ((string)(this["uupath"]));
            }
            set {
                this["uupath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\Admin\\AppData\\Local\\oopz\\oopz.exe")]
        public string oopzpath {
            get {
                return ((string)(this["oopzpath"]));
            }
            set {
                this["oopzpath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E:\\Program Files (x86)\\Steam\\steam.exe")]
        public string steampath {
            get {
                return ((string)(this["steampath"]));
            }
            set {
                this["steampath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string shortcut {
            get {
                return ((string)(this["shortcut"]));
            }
            set {
                this["shortcut"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string audioDeviceId {
            get {
                return ((string)(this["audioDeviceId"]));
            }
            set {
                this["audioDeviceId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool audioSwitchEnabled {
            get {
                return ((bool)(this["audioSwitchEnabled"]));
            }
            set {
                this["audioSwitchEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool restoreLastSelection {
            get {
                return ((bool)(this["restoreLastSelection"]));
            }
            set {
                this["restoreLastSelection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool winKeyDisabled {
            get {
                return ((bool)(this["winKeyDisabled"]));
            }
            set {
                this["winKeyDisabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool inputMethodEnglish {
            get {
                return ((bool)(this["inputMethodEnglish"]));
            }
            set {
                this["inputMethodEnglish"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool altShiftDisabled {
            get {
                return ((bool)(this["altShiftDisabled"]));
            }
            set {
                this["altShiftDisabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool optimizeWinKey {
            get { return ((bool)(this["optimizeWinKey"])); }
            set { this["optimizeWinKey"] = value; }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool optimizeInputMethod {
            get { return ((bool)(this["optimizeInputMethod"])); }
            set { this["optimizeInputMethod"] = value; }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool optimizeAltShift {
            get { return ((bool)(this["optimizeAltShift"])); }
            set { this["optimizeAltShift"] = value; }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool optimizeAudioOutput {
            get { return ((bool)(this["optimizeAudioOutput"])); }
            set { this["optimizeAudioOutput"] = value; }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool restoreWinKey {
            get { return ((bool)(this["restoreWinKey"])); }
            set { this["restoreWinKey"] = value; }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool restoreInputMethod {
            get { return ((bool)(this["restoreInputMethod"])); }
            set { this["restoreInputMethod"] = value; }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool restoreAltShift {
            get { return ((bool)(this["restoreAltShift"])); }
            set { this["restoreAltShift"] = value; }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool restoreAudioOutput {
            get { return ((bool)(this["restoreAudioOutput"])); }
            set { this["restoreAudioOutput"] = value; }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int optimizeMode {
            get { return ((int)(this["optimizeMode"])); }
            set { this["optimizeMode"] = value; }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int restoreMode {
            get { return ((int)(this["restoreMode"])); }
            set { this["restoreMode"] = value; }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool optimizeWinKeyDisabled {
            get { return ((bool)(this["optimizeWinKeyDisabled"])); }
            set { this["optimizeWinKeyDisabled"] = value; }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool optimizeInputEnglish {
            get { return ((bool)(this["optimizeInputEnglish"])); }
            set { this["optimizeInputEnglish"] = value; }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool optimizeAltShiftDisabled {
            get { return ((bool)(this["optimizeAltShiftDisabled"])); }
            set { this["optimizeAltShiftDisabled"] = value; }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool optimizeAudioSwitch {
            get { return ((bool)(this["optimizeAudioSwitch"])); }
            set { this["optimizeAudioSwitch"] = value; }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool restoreWinKeyDisabled {
            get { return ((bool)(this["restoreWinKeyDisabled"])); }
            set { this["restoreWinKeyDisabled"] = value; }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool restoreInputEnglish {
            get { return ((bool)(this["restoreInputEnglish"])); }
            set { this["restoreInputEnglish"] = value; }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool restoreAltShiftDisabled {
            get { return ((bool)(this["restoreAltShiftDisabled"])); }
            set { this["restoreAltShiftDisabled"] = value; }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool restoreAudioSwitch {
            get { return ((bool)(this["restoreAudioSwitch"])); }
            set { this["restoreAudioSwitch"] = value; }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string optimizeAudioDeviceId {
            get { return ((string)(this["optimizeAudioDeviceId"])); }
            set { this["optimizeAudioDeviceId"] = value; }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string restoreAudioDeviceId {
            get { return ((string)(this["restoreAudioDeviceId"])); }
            set { this["restoreAudioDeviceId"] = value; }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool startOneClickOptimize {
            get { return ((bool)(this["startOneClickOptimize"])); }
            set { this["startOneClickOptimize"] = value; }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool closeOneClickRestore {
            get { return ((bool)(this["closeOneClickRestore"])); }
            set { this["closeOneClickRestore"] = value; }
        }
    }
}
